- name: Realizar backup del pfSense con pfbackup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ejecutar comando pfbackup
      shell: >
        export PATH=$PATH:/snap/bin &&
        /snap/bin/pfbackup -U https://{{ pfsense_ip }}:4433
        -u {{ pfsense_username }}
        -p '{{ pfsense_password }}'
        -f /home/user1/ansible/backup/{{ backup_file }}
        --no-verify
      become: yes
      become_user: root
      register: pfbackup_output

    - name: Mostrar resultado del backup
      debug:
        msg: "{{ pfbackup_output.stdout }}"
