- name: Backup del firewall pfSense
  hosts: all
  tasks:
    - name: Autenticarse en pfSense
      uri:
        url: "https://{{ ansible_host }}/index.php"
        method: POST
        body: "usernamefld={{ pfsense_username }}&passwordfld={{ pfsense_password }}&login=Login"
        headers:
          Content-Type: application/x-www-form-urlencoded
        validate_certs: no
        return_content: yes
        status_code: 200
      register: login_response

    - name: Extraer cookies de sesión
      set_fact:
        session_cookies: "{{ login_response.cookies }}"

    - name: Descargar el backup de pfSense
      uri:
        url: "https://{{ ansible_host }}/diag_backup.php"
        method: GET
        headers:
          Cookie: "{{ session_cookies }}"
        validate_certs: no
        return_content: yes
      register: backup_response

    - name: Guardar backup en un archivo
      copy:
        content: "{{ backup_response.content }}"
        dest: "/tmp/pfsense-backup-{{ ansible_date_time.date }}.xml"

